---
- name: create directory file on all nodes
  hosts: Server1:Server2

  tasks:
  - name: create directory
    copy:
      content: Hello from Ansible! 
      dest: /home/ec2-user/opt/devops/info.txt
...