---
  - name: Update static page
    copy:
      src: static-page.html
      dest: /var/www/html/static_page.html

  - name: Update Dynamic page
    template:
      src: dynamic-template.j2
      dest: /var/www/html/dynamic_template.html
... 